// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vgt_saga_orders.Models;

#nullable disable

namespace vgt_saga_orders.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    partial class SagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vgt_saga_orders.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BookFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BookTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("FullBookFlight")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FullBookHotel")
                        .HasColumnType("boolean");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LesserChildren")
                        .HasColumnType("integer");

                    b.Property<int>("MidChildren")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int>("OldChildren")
                        .HasColumnType("integer");

                    b.Property<bool?>("Payment")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<bool?>("TempBookFlight")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TempBookHotel")
                        .HasColumnType("boolean");

                    b.Property<string>("TripFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TripTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
